services:
  common:
    image: 18f-zscaler-drupal:10-apache
    networks:
      - weather.gov
    links:
      - database:database
    environment:
      - DRUPAL_DB_NAME=weathergov
      - DRUPAL_DB_USERNAME=drupal
      - DRUPAL_DB_PASSWORD=drupal
      - DRUPAL_DB_HOST=database
      - DRUPAL_DB_PORT=3306
    volumes:
      - ./modules:/opt/drupal/web/modules
      - ./themes:/opt/drupal/web/themes
      - ./default-site:/opt/drupal/web/sites/default/
      - ./config:/config
