version: '3'

services:
  database:
    image: mariadb:10
    networks:
      - weather.gov
    environment:
      MYSQL_DATABASE: weathergov
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: drupal

  drupal:
    build: .
    extends:
      file: docker-compose.cms-config.yml
      service: common
    ports:
      - 8080:80

  install-site:
    profiles: ["install site"]
    extends:
      file: docker-compose.cms-config.yml
      service: common
    entrypoint: bash -c "composer require drush/drush && drush site-install minimal --existing-config --account-pass=root -y"

  import-config:
    profiles: ["import config"]
    extends:
      file: docker-compose.cms-config.yml
      service: common
    entrypoint: bash -c "composer require drush/drush && drush config:import -y"

  export-config:
    profiles: ["export config"]
    extends:
      file: docker-compose.cms-config.yml
      service: common
    entrypoint: bash -c "composer require drush/drush && drush config:export -y"

networks:
  weather.gov:
