version: '3'

services:
  database:
    image: mariadb:10
    networks:
      - weather.gov
    environment:
      MYSQL_DATABASE: weathergov
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: drupal

  drupal:
    image: 18f-zscaler-drupal:10-apache
    build: .
    networks:
      - weather.gov
    ports:
      - 8080:80
    links:
      - database:database
    volumes:
      - ./themes:/var/www/html/themes
networks:
  weather.gov:
