version: '3'

services:
  database:
    image: mariadb:10
    networks:
      - weather.gov
    environment:
      MYSQL_DATABASE: weathergov
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: drupal

  drupal:
    image: 18f-zscaler-drupal:10-apache
    build: .
    networks:
      - weather.gov
    ports:
      - 8080:80
    links:
      - database:database
    environment:
      - DRUPAL_DB_NAME=weathergov
      - DRUPAL_DB_USERNAME=drupal
      - DRUPAL_DB_PASSWORD=drupal
      - DRUPAL_DB_HOST=database
      - DRUPAL_DB_PORT=3306
    volumes:
      - ./themes:/var/www/html/themes
      - ./drupal-volume/modules:/opt/drupal/web/modules
      - ./drupal-volume/profiles:/opt/drupal/web/profiles
      - ./drupal-volume/themes:/opt/drupal/web/themes
      - ./drupal-volume/default-site:/opt/drupal/web/sites/default/
networks:
  weather.gov:
